# .travis.yml
language: generic
sudo: required
addons:
  apt:
    packages:
    - lftp

install:
 - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.24/hugo_0.24_Linux-64bit.deb
 - sudo dpkg -i /tmp/hugo.deb

script:
 - hugo --baseUrl $HUGO_BASEURL

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
