#baseUrl = "http://tufokan.cshorvath.com"
languageCode = "hu-hu"

title = "Tű Fokán Művészeti Fesztivál 2017. július 5-9. Garáb"
theme = "hugo-bootswatch"

[params]
[[menu.main]]
name = "Rólunk"
url = "/"
identifier = "about"
weight = 10
