baseUrl = "http://tufokan.cshorvath.com"
languageCode = "hu-hu"

title = "Tű Fokán Művészeti Fesztivál 2017"
theme = "hugo-bootswatch"

paginate = 10

[params]


# Menu links that appear on the left sidebar
[[menu.main]]
name = "Főoldal"
url = "/"
weight = -200
[[menu.main]]
name = "Program"
url = "/program/"
weight = -170
[[menu.main]]
name = "Fellépők"
url = "/artist/"
weight = -160
[[menu.main]]
name = "Információk"
url = "/jegyek/"
weight = -150
[[menu.main]]

name = "Kontakt"
url = "/kontakt/"
weight = -120
